export const translations = {
  pt: {
    Dashboard: {
      tab: {
        overview: "Página Inicial",
        events: "Eventos",
        clusters: "Grupos",
        reports: "Relatórios & SLA",
        settings: "Definições",
      },
      overview: {
        button: {
          new_service: "Novo serviço",
          add_service: "Adicionar Web Service",
          add_server: "Adicionar Servidor",
          add_container: "Adicionar Container",
          cancel: "Cancelar",
          create_service: "Criar Serviço",
        },
        service: {
          databse: "Configurar Banco de Dados",
          web_service: "Adicionar Web Service",
          server: "Adicionar Servidor",
          computer: "Computador",
          container: "Adicionar Container",
        },
        text: {
          title: "Painel de Controle",
          subtitle: "Monitore e gerencie seus serviços",
          services: "Serviços",
          services_description: "Selecione um serviço para configurar.",
          no_services: "Nenhum serviço encontrado",
          config_serive_details: "Configure os detalhes do novo serviço",
          search_service: "Buscar serviço...",
          loading: "Carregando...",
          error: "Erro ao carregar",
        },
      },
    },
    PCStatus: {
      waiting: "Aguardando dados do sistema...",
      system_status: "Status do Sistema",
      cpu: "CPU",
      memory: "Memória",
      free_of: "livres de ",
      os: "Sistema operacional",
      uptime: "Tempo de atividade",
      detailed_info: "Informações Detalhadas",
      processor: "Processador",
      cores: "Núcleos",
      model: "Modelo",
      system: "Sistema",
      version: "Versão",
      ip_address: "Endereço IP",
    }
  },
  en: {
    Dashboard: {
      tab: {
        overview: "Overview",
        events: "Events",
        clusters: "Clusters",
        reports: "Reports",
        settings: "Settings",
      },
      overview: {
        button: {
          new_service: "New Service",
          add_service: "Add Web Service",
          add_server: "Add Server",
          add_container: "Add Container",
          cancel: "Cancel",
          create_service: "Create Service",
        },
        service: {
          databse: "Configure Database",
          web_service: "Add Web Service",
          server: "Add Server",
          computer: "Computer",
          container: "Add Container",
        },
        text: {
          title: "Dashboard",
          subtitle: "Monitor and manage your services",
          services: "Services",
          services_description: "Select a service to configure.",
          no_services: "No services found",
          config_serive_details: "Configure the details of the new service",
          search_service: "Search service...",
          loading: "Loading...",
          error: "Error loading",
        },
      },
    },
    PCStatus: {
      waiting: "Waiting for system data...",
      system_status: "System Status",
      cpu: "CPU",
      memory: "Memory",
      free_of: "{free} free of {total}",
      os: "Operating system",
      uptime: "Uptime",
      detailed_info: "Detailed Information",
      processor: "Processor",
      cores: "Cores",
      model: "Model",
      system: "System",
      version: "Version",
      ip_address: "IP Address",
    },
  },
  fr: {
    Dashboard: {
      tab: {
        overview: "Accueil",
        events: "Événements",
        clusters: "Groupes",
        reports: "Rapports & SLA",
        settings: "Paramètres",
      },
      overview: {
        button: {
          new_service: "Nouveau service",
          add_service: "Ajouter un service Web",
          add_server: "Ajouter un serveur",
          add_container: "Ajouter un conteneur",
          cancel: "Annuler",
          create_service: "Créer un service",
        },
        service: {
          databse: "Configurer la base de données",
          web_service: "Ajouter un service Web",
          server: "Ajouter un serveur",
          computer: "Ordinateur",
          container: "Ajouter un conteneur",
        },
        text: {
          title: "Tableau de bord",
          subtitle: "Surveillez et gérez vos services",
          services: "Services",
          services_description: "Sélectionnez un service à configurer.",
          no_services: "Aucun service trouvé",
          config_serive_details: "Configurez les détails du nouveau service",
          search_service: "Rechercher un service...",
          loading: "Chargement...",
          error: "Erreur de chargement",
        },
      },
    },
    PCStatus: {
      waiting: "En attente des données système...",
      system_status: "État du système",
      cpu: "CPU",
      memory: "Mémoire",
      free_of: "{free} libres sur {total}",
      os: "Système d’exploitation",
      uptime: "Temps de fonctionnement",
      detailed_info: "Informations détaillées",
      processor: "Processeur",
      cores: "Cœurs",
      model: "Modèle",
      system: "Système",
      version: "Version",
      ip_address: "Adresse IP",
    },
  },
} as const

export type Language = keyof typeof translations
export type TranslationSchema = typeof translations[Language]
