import { Service } from "@/src/types/interfaces"

interface propProvider {
    service: Service,
    baseUrl: string
}

export const providersWebHook = ({ service, baseUrl }: propProvider) => {
    const providers = [
        // DevOps
        {
            id: "github",
            host: `${baseUrl}/webhook/github/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/github/github-original.svg",
            label: "GitHub",
            status: true,
            color: "text-gray-300",
            category: "DevOps",
            description: "Push, pull requests, issues events",
        },
        {
            id: "gitlab",
            host: `${baseUrl}/webhook/gitlab/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/gitlab/gitlab-original.svg",
            label: "GitLab",
            status: false,
            color: "text-orange-400",
            category: "DevOps",
            description: "Commits, pipelines, merge requests",
        },
        {
            id: "bitbucket",
            host: `${baseUrl}/webhook/bitbucket/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/bitbucket/bitbucket-original.svg",
            label: "Bitbucket",
            status: false,

            color: "text-blue-500",
            category: "DevOps",
            description: "Repository events, deploys, merges",
        },
        {
            id: "jenkins",
            host: `${baseUrl}/webhook/jenkins/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/jenkins/jenkins-original.svg",
            label: "Jenkins",
            status: false,
            color: "text-blue-400",
            category: "DevOps",
            description: "CI/CD job triggers",
        },
        {
            id: "grafana",
            host: `${baseUrl}/webhook/grafana/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/grafana/grafana-original.svg",
            label: "Grafana",
            status: false,
            color: "text-orange-500",
            category: "DevOps",
            description: "Dashboard alerts via webhook",
        },
        {
            id: "prometheus",
            host: `${baseUrl}/webhook/prometheus/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/prometheus/prometheus-original.svg",
            label: "Prometheus",
            status: false,
            color: "text-red-500",
            category: "DevOps",
            description: "Alertmanager webhook events",
        },
        {
            id: "slack",
            host: `${baseUrl}/webhook/slack/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/slack/slack-original.svg",
            label: "Slack",
            status: false,
            color: "text-purple-400",
            category: "Communication",
            description: "Channel messages and notifications",
        },
        {
            id: "teams",
            host: `${baseUrl}/webhook/teams/${service.type}/${service.id}`,
            logo: "https://cdn.worldvectorlogo.com/logos/microsoft-teams-1.svg",
            label: "Microsoft Teams",
            status: false,
            color: "text-blue-500",
            category: "Communication",
            description: "Team notifications and alerts",
        },
        {
            id: "stripe",
            host: `${baseUrl}/webhook/stripe/${service.type}/${service.id}`,
            logo: "https://cdn.worldvectorlogo.com/logos/stripe-4.svg",
            label: "Stripe",
            color: "text-purple-500",
            category: "Payments",
            description: "Payment events and subscriptions",
        },
        {
            id: "azure",
            host: `${baseUrl}/webhook/azure/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/azure/azure-original.svg",
            label: "Azure Monitor",
            color: "text-blue-500",
            status: false,
            category: "Cloud",
            description: "Monitoring and alert rules",
        },
        {
            id: "gcp",
            host: `${baseUrl}/webhook/gcp/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/googlecloud/googlecloud-original.svg",
            label: "Google Cloud Monitoring",
            status: false,
            color: "text-red-500",
            category: "Cloud",
            description: "Cloud operations and alerts",
        },
        {
            id: "sentry",
            host: `${baseUrl}/webhook/sentry/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/sentry/sentry-original.svg",
            label: "Sentry",
            color: "text-red-400",
            status: false,
            category: "Monitoring",
            description: "Error tracking and alerts",
        },
        {
            id: "datadog",
            host: `${baseUrl}/webhook/datadog/${service.type}/${service.id}`,
            logo: "https://cdn.worldvectorlogo.com/logos/datadog-1.svg",
            label: "Datadog",
            color: "text-purple-600",
            status: false,

            category: "Monitoring",
            description: "Infrastructure monitoring",
        },

        // Others
        {
            id: "trello",
            host: `${baseUrl}/webhook/trello/${service.type}/${service.id}`,
            logo: "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/trello/trello-plain.svg",
            label: "Trello",
            color: "text-blue-500",
            status: false,
            category: "Productivity",
            description: "Board and card changes",
        },
        {
            id: "zapier",
            host: `${baseUrl}/webhook/zapier/${service.type}/${service.id}`,
            logo: "https://cdn.worldvectorlogo.com/logos/zapier.svg",
            label: "Zapier",
            color: "text-orange-400",
            category: "Automation",
            status: false,
            description: "Workflow automation triggers",
        },
        {
            id: "ifttt",
            host: `${baseUrl}/webhook/ifttt/${service.type}/${service.id}`,
            logo: "https://cdn.worldvectorlogo.com/logos/ifttt.svg",
            label: "IFTTT",
            status: false,
            color: "text-blue-400",
            category: "Automation",
            description: "Service-to-service automations",
        },
    ];

    return providers
}