FROM node:22.16.0 AS builder
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm ci
COPY . .

FROM node:22.16.0-slim AS runner
WORKDIR /app
ENV NODE_ENV=production

USER root

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    iputils-ping \
    btop \
    htop \
    net-tools \
    dnsutils \
    curl \
    wget \
    python3 \
    python3-venv \
    python3-pip && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN python3 -m venv /opt/venv && \
    /opt/venv/bin/pip install --no-cache-dir --upgrade pip && \
    /opt/venv/bin/pip install --no-cache-dir scapy requests netaddr

RUN useradd -ms /bin/bash infraWatch
USER infraWatch

COPY --from=builder /app/public ./public
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/server.js ./server.js

EXPOSE 3001
CMD ["node", "server.js"]
